on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: 
      - ubuntu-20.04

    steps:
      - name: check rerun
        run: |
          if [ "$GITHUB_RUN_ATTEMPT" -gt 1 ]; then
            echo "This is a rerun."
            exit 1
          fi
