on:
  workflow_call:
    inputs:
      STACK:
        required: true
        type: string
jobs:
  deploy:
    runs-on: 
      - ubuntu-20.04

    steps:
      - name: check rerun
        run: |
          if [ "$GITHUB_RUN_ATTEMPT" -gt 1 ] && [${{ inputs.STACK }} == "dev"]; then
            echo "This is a rerun."
            exit 1
          else
            echo "no problem"
          fi
